version: 2.0
- command:
   name: release
   execute:
      - nim others/build.nims x86_64-linux-gnu
   description: Build Steam Sky in release mode
- command:
   name: windows
   execute:
      - others/build.nims x86_64-windows
   description: Build Steam Sky release for Windows on Linux
   flags:
      - unixonly
- command:
   name: push
   execute:
      - fossil push
      - fossil git export --force
   description: Update remote Fossil repository and its Git mirror
