language: c

branches:
   only:
      - master

services:
   - docker

matrix:
   include:
      - os: linux
        env:
         - FILENAME=steamsky-dev-Linux-64.tar.gz
        install:
         - echo "$DOCKERPASS" | docker login https://docker.pkg.github.com -u "$DOCKERUSER" --password-stdin
         - docker pull docker.pkg.github.com/thindil/tashy/tashy:8.6.7
        script:
         - docker run -v $(pwd):/app docker.pkg.github.com/thindil/tashy/tashy:8.6.7 /bin/sh -c "apt-get update && apt-get install -y libxmlada-schema9-dev libxmlada-input9-dev && cd /app && others/build.tcl"
         - tar -czf steamsky-dev-Linux-64.tar.gz usr
      - os: windows
        env:
         - FILENAME=steamsky-dev-Windows-64.zip
        install:
         - export "PATH=/c/GNAT/bin:/c/Tcl86/bin:$PATH";
         - wget "https://www.dropbox.com/s/99bf04k6hvh05yr/gnattcl.7z?dl=0" -O gnattcl.7z;
         - 7z x gnattcl.7z -oc:/;
        script:
         - gprbuild -P steamsky.gpr -XMode=release
         - 7z a -tzip steamsky-dev-Windows-64.zip bin;

before_deploy:
    - "if [[ $FILENAME == \"steamsky-dev-Linux-64.tar.gz\" ]]; then git tag -f travis-dev-build && git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${KEY}@github.com/${TRAVIS_REPO_SLUG}.git && git push -f gh travis-dev-build && git remote remove gh; fi"
    - export "TRAVIS_TAG=travis-dev-build";

deploy:
  provider: releases
  skip_cleanup: true
  api-key: $KEY
  file:
   - $FILENAME
  name: Continuous Integration build
  body: Development build of 6.0 built by Travis CI.
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: travis-dev-build
  on:
   branch: master
