language: c

branches:
   only:
      - 5.0

services:
   - docker

matrix:
   include:
      - os: linux
        env:
         - EXTENSION=tar.gz
        install:
         - docker pull thindil/gnat-gtkada;
        script:
         - docker run -v $(pwd):/app thindil/gnat-gtkada /bin/sh -c "cd /app && ./others/build.sh release"
         - tar -czf steamsky-stable.tar.gz usr
      - os: windows
        env:
         - EXTENSION=zip
        install:
         - export "PATH=/c/GNAT/bin:/c/GtkAda/bin:$PATH";
         - export "GPR_PROJECT_PATH=/c/GtkAda/lib/gnat";
         - wget "https://www.dropbox.com/s/nwxl8so7mukbnmp/gnat.7z?dl=0" -O gnat.7z;
         - 7z x gnat.7z -oc:/;
         - wget "https://www.dropbox.com/s/wnjswjwh64w33vd/gtkada.7z?dl=0" -O gtkada.7z;
         - 7z x gtkada.7z -oc:/;
        script:
         - gprbuild -P steamsky.gpr -XMode=release
         - 7z a -tzip steamsky-stable.zip bin;

before_deploy:
    - "if [[ $EXTENSION == \"tar.gz\" ]]; then git tag -f travis-stable-build && git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${KEY}@github.com/${TRAVIS_REPO_SLUG}.git && git push -f gh travis-stable-build && git remote remove gh; fi"
    - export "TRAVIS_TAG=travis-stable-build";

deploy:
  provider: releases
  skip_cleanup: true
  api-key: $KEY
  file:
   - steamsky-stable.$EXTENSION
  name: Continuous Integration stable build
  body: Stable build of $TRAVIS_BRANCH built by Travis CI.
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: travis-stable-build
  on:
   branch: 5.0

notifications:
  email: false
