name: Continuous Integration - development version

on:
  push:
    branches: [ master ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/build:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run AdaControl - check names and parameters
      run: |
         cd nim
         nim debug
         cd ..
         mkdir obj
         cd obj
         adactl -f ../others/adacontrol/rules1.aru -p ../steamsky.gpr -o ../adacontrol.log -r steamsky-tcl-cargv-chelper-unicode-sax-dom-input_sources
         cd ..

    - name: Upload the log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
         name: adacontrol.log
         path: adacontrol.log

    - name: Generate tests
      run: gnattest -P steamsky.gpr

    - name: Build the tests
      run: gprbuild -P tests/driver/test_driver.gpr

    - name: Run the tests
      run: others/tests.tcl 30

  build_linux:

    if: ${{ always() }}
    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/build:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-linux-gnu

    - name: Compress the artifact
      run: tar -cf steamsky-development-linux.tar -C release steamsky-linux

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: steamsky-development-linux.tar
         path: steamsky-development-linux.tar

  build_windows:

    if: ${{ always() }}
    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/buildwin64:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-windows

    - name: Compress the artifact
      run: tar -cf steamsky-development-windows.tar -C release steamsky-windows

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: steamsky-development-windows.tar
         path: steamsky-development-windows.tar
