name: Continuous Integration - development version

on:
  push:
    branches: [ master ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate tests
      run: gnattest -P steamsky.gpr

    - name: Build the tests
      run: gprbuild -P tests/driver/test_driver.gpr

    - name: Run the tests
      run: others/tests.tcl 30

  build_linux:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-linux-gnu

    - name: Compress the artifact
      run: tar -cf steamsky-development-linux.tar -C release steamsky-linux

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: steamsky-development-linux.tar
         path: steamsky-development-linux.tar

  build_windows:

    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuildwin64

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the program
      run: others/build.tcl x86_64-windows

    - name: Compress the artifact
      run: tar -cf steamsky-development-windows.tar -C release steamsky-windows

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
         name: steamsky-development-windows.tar
         path: steamsky-development-windows.tar
